version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: employee_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - employee_network

  backend:
    build: ./backend
    container_name: employee_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - employee_network
    command: npm run dev
    environment:
      - MONGO_URI=mongodb://mongodb:27017/employee_management_db

  frontend:
    build: ./frontend
    container_name: employee_frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - employee_network
    stdin_open: true
    tty: true

volumes:
  mongodb_data:

networks:
  employee_network:
    driver: bridge